In [1]:
import numpy as np

NumPy 定义了一个 n 维数组对象，简称 ndarray 对象，它是一个一系列相同类型元素组成的数组集合。数组中的每个元素都占有大小相同的内存块，您可以使用索引或切片的方式获取数组中的每个元素。
创建ndarray对象
通过 NumPy 的内置函数 array() 可以创建 ndarray 对象，其语法格式如下：
numpy.array(object, dtype = None, copy = True, order = None,ndmin = 0)

下面表格对其参数做了说明：

参数说明
|序号|	参数|	描述说明|
|:--:|:--:|:--:|
|1	|object	|表示一个数组序列。|
|2	|dtype	|可选参数，通过它可以更改数组的数据类型。|
|3	|copy	|可选参数，表示数组能否被复制，默认是 True。|
|4	|order	|以哪种内存布局创建数组，有 3 个可选值，分别是 C(行序列)/F(列序列)/A(默认)。|
|5	|ndim	|用于指定数组的维度。|


In [ ]:
a = np.array([1, 2, 3])
a

array([1, 2, 3])

In [4]:
type(a)

numpy.ndarray

In [ ]:
b = np.array([[1, 2, 3], [4, 5, 6]])
b

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
c = np.array([2, 4, 6, 8], dtype="complex")
c

array([2.+0.j, 4.+0.j, 6.+0.j, 8.+0.j])

ndim查看数组维数

In [ ]:
a1 = np.array([1, 2, 3], ndmin=2)
a1

array([[1, 2, 3]])

In [ ]:
a2 = np.array([[1, 2, 3, 4], [4, 5, 6, 7], [6, 7, 8, 9]])
a2.ndim

2

reshape数组变维
数组的形状指的是多维数组的行数和列数。Numpy 模块提供 reshape() 函数可以改变多维数组行数和列数，从而达到数组变维的目的。因此数组变维即对数组形状的重塑，如图1所示：

Numpy reshape函数变维

![image.png](https://c.biancheng.net/uploads/allimg/210712/1145091042-0.jpg)

reshape() 函数可以接受一个元组作为参数，用于指定了新数组的行数和列数，示例如下：

In [ ]:
e = np.array([[1, 2], [3, 4], [5, 6]])
e

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
e = e.reshape(2, 3)
e

array([[1, 2, 3],
       [4, 5, 6]])