### ndarray.shape
shape 属性的返回值一个由数组维度构成的元组，比如 2 行 3 列的二维数组可以表示为(2,3)，该属性可以用来调整数组维度的大小。

In [1]:
import numpy as np

In [ ]:
a = np.array([[2, 4, 6], [3, 5, 7]])
a.shape

(2, 3)

In [ ]:
a.shape = (3, 2)  # 改变形状
a

array([[2, 4],
       [6, 3],
       [5, 7]])

### ndarray.reshape()
NumPy 还提供了一个调整数组形状的 reshape() 函数。

In [5]:
b = a.reshape(3, 2)
b

array([[2, 4],
       [6, 3],
       [5, 7]])

### ndarray.ndim
该属性返回的是数组的维数

In [6]:
c = np.arange(24)
c, c.ndim

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23]),
 1)

In [7]:
# 对数组进行变维
e = c.reshape(2, 4, 3)
e, e.ndim

(array([[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8],
         [ 9, 10, 11]],
 
        [[12, 13, 14],
         [15, 16, 17],
         [18, 19, 20],
         [21, 22, 23]]]),
 3)

### ndarray.itemsize
返回数组中每个元素的大小（以字节为单位）

In [ ]:
x = np.array([1, 2, 3, 4, 5], dtype=np.int8)
x.itemsize

1

In [ ]:
x2 = np.array([1, 2, 3, 4, 5], dtype=np.int64)
x2.itemsize

8

### ndarray.flags
返回 ndarray 数组的内存信息，比如 ndarray 数组的存储方式，以及是否是其他数组的副本等。

In [10]:
x.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False