#### numpy.empty()
numpy.empty() 创建未初始化的数组，可以指定创建数组的形状（shape）和数据类型（dtype）

In [1]:
import numpy as np

numpy.empty(shape, dtype = float, order = 'C')

它接受以下参数：
- shape：指定数组的形状；
- dtype：数组元素的数据类型，默认值是值 float；
- order：指数组元素在计算机内存中的储存顺序，默认顺序是“C”(行优先顺序)。


In [ ]:
np.empty((3, 2), dtype=int)  # 数组带有随机值，没有实际意义 且empty并不是创建空数组

array([[          0,           0],
       [ -261145056,         468],
       [          0, -2147483648]])

#### numpy.zeros()
该函数用来创建元素均为 0 的数组，同时还可以指定被数组的形状
numpy. zeros(shape,dtype=float,order="C")


参数说明
|参数名称	|说明描述|
|:--:|:--:|
|shape|	指定数组的形状大小。|
|dtype|	可选项，数组的数据类型|
|order|	“C”代表以行顺序存储，“F”则表示以列顺序存储|


In [3]:
a = np.zeros(6)
a

array([0., 0., 0., 0., 0., 0.])

In [4]:
b = np.zeros(6, dtype="complex64")
b

array([0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j], dtype=complex64)

In [ ]:
# 自定义类型
c = np.zeros((3, 3), dtype=[("x", "i4"), ("y", "i4")])
c

array([[(0, 0), (0, 0), (0, 0)],
       [(0, 0), (0, 0), (0, 0)],
       [(0, 0), (0, 0), (0, 0)]], dtype=[('x', '<i4'), ('y', '<i4')])

#### numpy.ones()
返回指定形状大小与数据类型的新数组，并且新数组中每项元素均用 1 填充

In [ ]:
np.ones((3, 2), dtype=int)

array([[1, 1],
       [1, 1],
       [1, 1]])

#### numpy.asarray()
asarray() 与 array() 类似，但是它比 array() 更为简单。asarray() 能够将一个 Python 序列转化为 ndarray 对象，语法格式如下：
numpy.asarray（sequence，dtype = None ，order = None ）

它接受下列参数：
- sequence：接受一个 Python 序列，可以是列表或者元组；
- dtype：可选参数，数组的数据类型；
- order：数组内存布局样式，可以设置为 C 或者 F，默认是 C。


In [ ]:
l = (1, 2, 3, 4, 5, 6, 7)
a = np.asanyarray(l)
a, type(a)

(array([1, 2, 3, 4, 5, 6, 7]), numpy.ndarray)

In [ ]:
l = [1, 2, 3, 4, 5, 6, 7]
a = np.asanyarray(l)
a, type(a)

(array([1, 2, 3, 4, 5, 6, 7]), numpy.ndarray)

In [ ]:
l = [[1, 2, 3, 4, 5, 6, 7], [8, 9]]
a = np.asanyarray(l)
a, type(a)

C:\Users\abner\AppData\Local\Temp\ipykernel_32808\2203335303.py:2: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  a = np.asanyarray(l)


(array([list([1, 2, 3, 4, 5, 6, 7]), list([8, 9])], dtype=object),
 numpy.ndarray)

> 警告是因为 numpy 在处理不规则嵌套序列（ragged nested sequences）时，默认行为已经发生了变化。不规则嵌套序列是指包含不同长度或形状的列表或元组的列表。numpy 现在默认不再支持这种不规则嵌套序列，除非你显式地指定 dtype=object。

> 要解决这个警告，可以在调用 np.asanyarray 时显式地指定 dtype=object。这样可以确保 numpy 将整个嵌套序列作为一个对象数组来处理，而不是尝试将其转换为多维数组。

In [11]:
l = [[1, 2, 3, 4, 5, 6, 7], [8, 9]]
a = np.asanyarray(l, dtype=object)
a, type(a)

(array([list([1, 2, 3, 4, 5, 6, 7]), list([8, 9])], dtype=object),
 numpy.ndarray)

#### numpy.frombuffer()
表示使用指定的缓冲区创建数组。下面给出了该函数的语法格式：

`numpy.frombuffer(buffer, dtype = float, count = -1, offset = 0)`

它的参数说明如下所示：

- buffer：将任意对象转换为流的形式读入缓冲区；
- dtype：返回数组的数据类型，默认是 float32；
- count：要读取的数据数量，默认为 -1 表示读取所有数据；
- offset：读取数据的起始位置，默认为 0。

In [ ]:
s = b"hello world"
type(s)

bytes

In [13]:
a = np.frombuffer(s, dtype="S1")
a, type(a)

(array([b'h', b'e', b'l', b'l', b'o', b' ', b'w', b'o', b'r', b'l', b'd'],
       dtype='|S1'),
 numpy.ndarray)

#### numpy.fromiter()
该方法可以把迭代对象转换为 ndarray 数组，其返回值是一个一维数组。
numpy.fromiter(iterable, dtype, count = -1)

参数说明如下：

参数描述
|参数名称	| 描述说明|
|:--:|:--:|
|iterable	|可迭代对象。|
|dtype	    |返回数组的数据类型。|
|count	    |读取的数据数量，默认为 -1，读取所有数据。|




In [14]:
# 使用内置 range() 函数创建列表对象，然后使用迭代器创建 ndarray 对象
ll = range(6)
i = iter(ll)
arr = np.fromiter(i, dtype=float)
arr

array([0., 1., 2., 3., 4., 5.])