在 NumPy 中，如果想要访问，或修改数组中的元素，您可以采用索引或切片的方式，比如使用从 0 开始的索引依次访问数组中的元素，这与 Python 的 list 列表是相同的。
NumPy 提供了多种类型的索引方式，常用方式有两种：基本切片与高级索引。

#### 基本切片
NumPy 内置函数 slice() 可以用来构造切片对象，该函数需要传递三个参数值分别是 start（起始索引）、stop（终止索引） 和 step（步长） ，通过它可以实现从原数组的上切割出一个新数组。

In [ ]:
import numpy as np

In [ ]:
a = np.arange(10)

In [ ]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
s = slice(2, 9, 3)
s

slice(2, 9, 3)

In [ ]:
a[s]

array([2, 5, 8])

In [ ]:
b = a[2:9:3]
b

array([2, 5, 8])

下面对冒号切片做简单地说明：
- 如果仅输入一个参数，则将返回与索引相对应的元素。 对于上述示例来说[3] 就会返回 3。
- 如果在其前面插入“:”如[:9]，则会返回 0-8 的所有数字（不包含9）。
- 如是 [2:] 则会返回 2-9 之间的数字。
- 如果在两个参数之间，如[2:9]，则对两个索引值之间的所有元素进行切片（不包括停止索引）。


In [ ]:
b1 = a[3]
b1

3

In [ ]:
a[2:]

array([2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
a[2:5]

array([2, 3, 4])

#### 多维数组切片

In [ ]:
a2 = np.array([[1, 2, 3], [3, 4, 5], [4, 5, 6]])
a2

array([[1, 2, 3],
       [3, 4, 5],
       [4, 5, 6]])

In [ ]:
a2[1:]

array([[3, 4, 5],
       [4, 5, 6]])

In [ ]:
# 注意：切片还可以使用省略号“…”，如果在行位置使用省略号，那么返回值将包含所有行元素，反之，则包含所有列元素。
a2[..., 1]  # 第二列

array([2, 4, 5])

In [ ]:
a2[1, ...]  # 第二行

array([3, 4, 5])

In [ ]:
a2[..., 1:]  # 第二列后的所有

array([[2, 3],
       [4, 5],
       [5, 6]])