NumPy 与 Python 的内置序列相比，它提供了更多的索引方式。除了在《Numpy切片和索引》一节用到索引方式外，在 NumPy 中还可以使用高级索引方式，比如整数数组索引、布尔索引以及花式索引，本节主要对上述三种索引方式做详细介绍。
高级索引返回的是数组的副本（深拷贝），而切片操作返回的是数组视图（浅拷贝）。

#### 1. 整数数组索引
整数数组索引，它可以选择数组中的任意一个元素，比如，选择第几行第几列的某个元素

In [1]:
import numpy as np

In [ ]:
x = np.array([[1, 2], [3, 4], [5, 6]])
# [0,1,2] 行索引 [0,1,0] 列索引
y = x[[0, 1, 2], [0, 1, 0]]
y

array([1, 4, 5])

对上述示例做简单分析：将行、列索引组合会得到 (0,0)、(1,1) 和 (2,0) ，它们分别对应着输出结果在原数组中的索引位置。

下面再看一组示例：获取了 4*3 数组中的四个角上元素，它们对应的行索引是 [0,0] 和 [3,3]，列索引是 [0,2] 和 [0,2]。

In [ ]:
b = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8], [9, 10, 11]])
r = np.array([[0, 0], [3, 3]])
c = np.array([[0, 2], [0, 2]])
c = b[r, c]
c

array([[ 0,  2],
       [ 9, 11]])

In [ ]:
d = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8], [9, 10, 11]])
# 对行列分别进行切片
e = d[1:4, 1:3]
e


array([[ 4,  5],
       [ 7,  8],
       [10, 11]])

In [ ]:
# 行使用基础索引 列使用高级索引
f = d[1:4, [1, 2]]
f

array([[ 4,  5],
       [ 7,  8],
       [10, 11]])

In [7]:
# 对行使用省略号
h = d[..., 1:]
h

array([[ 1,  2],
       [ 4,  5],
       [ 7,  8],
       [10, 11]])

#### 2. 布尔数组索引
当输出的结果需要经过布尔运算（如比较运算）时，此时会使用到另一种高级索引方式，即布尔数组索引。下面示例返回数组中大于 6 的的所有元素：

In [ ]:
x = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8], [9, 10, 11]])
x[x > 6]

array([ 7,  8,  9, 10, 11])

In [9]:
# 可以使用补码运算符来去除 NaN（即非数字元素）
a = np.array([1, 2, 3, np.nan, 5, 6])
a[~np.isnan(a)]

array([1., 2., 3., 5., 6.])

In [ ]:
# 删除数组中整数元素
a = np.array([1, 2 + 6j, 5, 3.5 + 5j])
a[np.iscomplex(a)]

array([2. +6.j, 3.5+5.j])

#### 3. 花式索引（拓展知识）
花式索引也可以理解为整数数组索引，但是它们之间又略有不同，下面通过示例做简单讲解。（本内容作为拓展知识了解即可）
花式索引也会生成一个新的副本。

当原数组是一维数组时，使用一维整型数组作为索引，那么索引结果就是相应索引位置上的元素。

In [ ]:
x = np.array([1, 2, 3, 4])
x[0]

1

In [13]:
# 如果原数组是二维数组，那么索引数组也需要是二维的，索引数组的元素值与被索引数组的每一行相对应
x = np.arange(32).reshape((8, 4))
# 分别对应 第四行数据 第二行数据 第一行数据 第七行数据
x[[4, 2, 1, 7]]

array([[16, 17, 18, 19],
       [ 8,  9, 10, 11],
       [ 4,  5,  6,  7],
       [28, 29, 30, 31]])

In [14]:
# 使用倒序索引数组
x[[-4, -2, -1, -7]]

array([[16, 17, 18, 19],
       [24, 25, 26, 27],
       [28, 29, 30, 31],
       [ 4,  5,  6,  7]])

In [15]:
# 同时使用多个索引数组，但这种情况下需要添加np.ix_
x[np.ix_([1, 5, 7, 2], [0, 3, 1, 2])]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

其中 [1,5,7,2] 代表行索引，而 [0,3,1,2] 表示与行索引相对应的列索引值，也就是行中的元素值会按照列索引值排序。比如，第一行元素，未排序前的顺序是 [4,5,6,7]，经过列索引排序后变成了 [4,7,5,6]。