#### 1. numpy.resize()
numpy.resize() 返回指定形状的新数组。

numpy.resize(arr, shape)

In [1]:
import numpy as np

In [3]:
a = np.array([[1, 2, 3], [4, 5, 6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
a.shape

(2, 3)

In [5]:
b = np.resize(a, (3, 2))
b, b.shape

(array([[1, 2],
        [3, 4],
        [5, 6]]),
 (3, 2))

In [7]:
b = np.resize(a, (3, 3))  # 修改b数组使其形状大于原始数组
b

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3]])

这里需要区别 resize() 和 reshape() 的使用方法，它们看起来相似，实则不同。resize 仅对原数组进行修改，没有返回值，而 reshape 不仅对原数组进行修改，同时返回修改后的结果。

In [8]:
x = np.arange(12)
x_resize = x.resize(2, 3, 2)
x, x_resize

(array([[[ 0,  1],
         [ 2,  3],
         [ 4,  5]],
 
        [[ 6,  7],
         [ 8,  9],
         [10, 11]]]),
 None)

In [9]:
x_shape = x.reshape(2, 3, 2)
x_shape

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

In [11]:
x

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

#### 2. numpy.append()
在数组的末尾添加值，它返回一个一维数组。
numpy.append(arr, values, axis=None)

参数说明：
- arr：输入的数组；
- values：向 arr 数组中添加的值，需要和 arr 数组的形状保持一致；
- axis：默认为 None，返回的是一维数组；当 axis =0 时，追加的值会被添加到行，而列数保持不变，若 axis=1 则与其恰好相反。

In [ ]:
a = np.array([[1, 2, 3], [4, 5, 6]])
np.append(a, [7, 8, 9])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
# 0 轴添加
np.append(a, [[7, 8, 9]], axis=0)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
# 1轴 添加
np.append(a, [[5, 5, 5], [7, 8, 9]], axis=1)

array([[1, 2, 3, 5, 5, 5],
       [4, 5, 6, 7, 8, 9]])

#### 3. numpy.insert()
表示沿指定的轴，在给定索引值的前一个位置插入相应的值，如果没有提供轴，则输入数组被展开为一维数组。
numpy.insert(arr, obj, values, axis)

参数说明：
- arr：要输入的数组
- obj：表示索引值，在该索引值之前插入 values 值；
- values：要插入的值；
- axis：指定的轴，如果未提供，则输入数组会被展开为一维数组。

In [ ]:
a = np.array([[1, 2], [3, 4], [5, 6]])
# 不提供axis的情况下 会将数组展开
np.insert(a, 3, [11, 12])

array([ 1,  2,  3, 11, 12,  4,  5,  6])

In [17]:
# 0 轴
np.insert(a, 1, [11], axis=0)

array([[ 1,  2],
       [11, 11],
       [ 3,  4],
       [ 5,  6]])

In [19]:
# 1轴
np.insert(a, 1, 11, axis=1)

array([[ 1, 11,  2],
       [ 3, 11,  4],
       [ 5, 11,  6]])

#### 4. numpy.delete()
该方法表示从输入数组中删除指定的子数组，并返回一个新数组。它与 insert() 函数相似，若不提供 axis 参数，则输入数组被展开为一维数组。
numpy.delete(arr, obj, axis)

参数说明：
- arr：要输入的数组；
- obj：整数或者整数数组，表示要被删除数组元素或者子数组；
- axis：沿着哪条轴删除子数组。

In [21]:
a = np.arange(12).reshape(3, 4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [22]:
np.delete(a, 5)

array([ 0,  1,  2,  3,  4,  6,  7,  8,  9, 10, 11])

In [23]:
np.delete(a, 1, axis=1)

array([[ 0,  2,  3],
       [ 4,  6,  7],
       [ 8, 10, 11]])

In [ ]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
np.delete(a, np.s_[::2])  # 删除经切片后的数组

array([ 2,  4,  6,  8, 10])

#### 5. numpy.argwhere()
该函数返回数组中非 0 元素的索引，若是多维数组则返回行、列索引组成的索引坐标。

In [26]:
x = np.arange(6).reshape(2, 3)
y = np.argwhere(x > 1)
x, y

(array([[0, 1, 2],
        [3, 4, 5]]),
 array([[0, 2],
        [1, 0],
        [1, 1],
        [1, 2]], dtype=int64))

#### 6. numpy.unique()
用于删除数组中重复的元素，其语法格式如下：

numpy.unique(arr, return_index, return_inverse, return_counts)

参数说明：
- arr：输入数组，若是多维数组则以一维数组形式展开；
- return_index：如果为 True，则返回新数组元素在原数组中的位置（索引）；
- return_inverse：如果为 True，则返回原数组元素在新数组中的位置（索引）；
- return_counts：如果为 True，则返回去重后的数组元素在原数组中出现的次数。

In [ ]:
a = np.array([5, 2, 6, 2, 7, 5, 6, 8, 2, 9])
a

array([5, 2, 6, 2, 7, 5, 6, 8, 2, 9])

In [ ]:
np.unique(a)  # 去重

array([2, 5, 6, 7, 8, 9])

In [30]:
u, indices = np.unique(a, return_index=True)  # 去重后的索引数组
u, indices

(array([2, 5, 6, 7, 8, 9]), array([1, 0, 2, 4, 7, 9], dtype=int64))

In [31]:
ui, indices = np.unique(a, return_inverse=True)  # 去重数组的下标
ui, indices

(array([2, 5, 6, 7, 8, 9]), array([1, 0, 2, 0, 3, 1, 2, 4, 0, 5], dtype=int64))

In [32]:
uc, indices = np.unique(a, return_counts=True)  # 去重元素的重复数量
uc, indices

(array([2, 5, 6, 7, 8, 9]), array([3, 2, 2, 1, 1, 1], dtype=int64))